// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StayIn.Api.Data;

#nullable disable

namespace StayinApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318132235_RemoveUserId1Shadow")]
    partial class RemoveUserId1Shadow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StayIn.Api.Models.Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccommodationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressBuilding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressPostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<int>("Beds")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.PrimitiveCollection<string>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "A Blok Kat:3",
                            AddressCity = "İzmir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Çeşme",
                            AddressPostalCode = "35930",
                            AddressRegion = "Ege",
                            AddressStreet = "Alaçatı Mahallesi, Sahil Caddesi No:45",
                            Amenities = "[\"Wifi\",\"Klima\",\"Havuz\",\"Jakuzi\",\"Deniz Manzaras\\u0131\",\"\\u00D6zel Plaj\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çeşme'nin en güzel sahilinde, deniz manzaralı modern daire. Havuz, jakuzi ve özel plaj erişimi mevcut.",
                            Guests = 4,
                            IsArchived = false,
                            Latitude = 38.322800000000001,
                            Longitude = 26.302499999999998,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800\",\"https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800\"]",
                            PlaceType = "Daire",
                            Price = 2500m,
                            Title = "Deniz Manzaralı Lüks Daire",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Kalkan",
                            AddressPostalCode = "07960",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Kalamar Mahallesi, Yalı Sokak No:12",
                            Amenities = "[\"Wifi\",\"Klima\",\"Havuz\",\"Bah\\u00E7e\",\"Mangal\",\"Deniz Manzaras\\u0131\",\"\\u00D6zel Otopark\"]",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            Beds = 5,
                            CreatedAt = new DateTime(2024, 11, 3, 14, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Kalkan'da özel havuzlu, geniş bahçeli lüks villa. Muhteşem deniz manzarası ve sessiz konum.",
                            Guests = 8,
                            IsArchived = false,
                            Latitude = 36.265599999999999,
                            Longitude = 29.408899999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800\",\"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800\"]",
                            PlaceType = "Villa",
                            Price = 5000m,
                            Title = "Modern Villa Havuz ve Bahçe",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Butik Otel",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Bodrum",
                            AddressPostalCode = "48400",
                            AddressRegion = "Ege",
                            AddressStreet = "Gümbet Mahallesi, Plaj Yolu No:8",
                            Amenities = "[\"Wifi\",\"Klima\",\"TV\",\"Kahvalt\\u0131\",\"Plaja Yak\\u0131n\",\"Restoran\"]",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            Beds = 3,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Bodrum'un kalbinde, plaja yürüme mesafesinde modern ve konforlu konaklama. Kahvaltı dahil.",
                            Guests = 6,
                            IsArchived = false,
                            Latitude = 37.034399999999998,
                            Longitude = 27.430499999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800\",\"https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800\"]",
                            PlaceType = "Ev",
                            Price = 3200m,
                            Title = "Plaja Sıfır Butik Otel",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Bungalov 5",
                            AddressCity = "Bolu",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Abant",
                            AddressPostalCode = "14100",
                            AddressRegion = "Karadeniz",
                            AddressStreet = "Göl Mahallesi, Doğa Yolu No:23",
                            Amenities = "[\"Wifi\",\"\\u015E\\u00F6mine\",\"Veranda\",\"G\\u00F6l Manzaras\\u0131\",\"Do\\u011Fa\",\"Mangal\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 5, 16, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Abant Gölü manzaralı, doğa ile iç içe huzurlu bungalov. Şömine, veranda ve orman manzarası.",
                            Guests = 3,
                            IsArchived = false,
                            Latitude = 40.616700000000002,
                            Longitude = 31.2667,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800\",\"https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800\"]",
                            PlaceType = "Kulübe",
                            Price = 1800m,
                            Title = "Doğa İçinde Bungalov",
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccommodationType = "Bütün mekan",
                            AddressCity = "İzmir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Alaçatı",
                            AddressPostalCode = "35937",
                            AddressRegion = "Ege",
                            AddressStreet = "Kemalpaşa Mahallesi, Taş Sokak No:7",
                            Amenities = "[\"Wifi\",\"Klima\",\"Bah\\u00E7e\",\"Mutfak\",\"Merkezi Konum\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 1,
                            CreatedAt = new DateTime(2024, 11, 2, 11, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Alaçatı çarşısına 5 dakika yürüme mesafesinde otantik taş ev. Şirin bahçe ve modern iç dekorasyon.",
                            Guests = 2,
                            IsArchived = false,
                            Latitude = 38.266599999999997,
                            Longitude = 26.3782,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800\"]",
                            PlaceType = "Daire",
                            Price = 2200m,
                            Title = "Alaçatı Merkezde Taş Ev",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            AccommodationType = "Özel oda",
                            AddressBuilding = "A Blok Kat:12",
                            AddressCity = "İstanbul",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Beşiktaş",
                            AddressPostalCode = "34347",
                            AddressRegion = "Marmara",
                            AddressStreet = "Ortaköy Mahallesi, Mecidiye Köprüsü Sokak No:15",
                            Amenities = "[\"Wifi\",\"Spa\",\"Restoran\",\"Oda Servisi\",\"Bo\\u011Faz Manzaras\\u0131\",\"Jakuzi\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 8, 30, 0, 0, DateTimeKind.Utc),
                            Description = "İstanbul Ortaköy'de Boğaz manzaralı suit oda. Spa, restoran ve özel hizmet.",
                            Guests = 2,
                            IsArchived = false,
                            Latitude = 41.047800000000002,
                            Longitude = 29.026700000000002,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800\"]",
                            PlaceType = "Otel Odası",
                            Price = 3500m,
                            Title = "Boğaz Manzaralı Lüks Suit",
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa Sunset",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Kaş",
                            AddressPostalCode = "07580",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Çukurbağ Yarımadası, Manzara Yolu No:34",
                            Amenities = "[\"Wifi\",\"Sonsuzluk Havuzu\",\"Klima\",\"Bah\\u00E7e\",\"Mangal\",\"Deniz Manzaras\\u0131\",\"Otopark\"]",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            Beds = 6,
                            CreatedAt = new DateTime(2024, 11, 3, 13, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kaş merkezine 10 dakika, sonsuzluk havuzlu, 5 yatak odalı lüks villa. Muhteşem gün batımı manzarası.",
                            Guests = 10,
                            IsArchived = false,
                            Latitude = 36.2014,
                            Longitude = 29.640999999999998,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800\"]",
                            PlaceType = "Villa",
                            Price = 6500m,
                            Title = "Kaş'ta Panoramik Deniz Manzaralı Villa",
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "B Blok Kat:5",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Konyaaltı",
                            AddressPostalCode = "07050",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Liman Mahallesi, Sahil Bulvarı No:88",
                            Amenities = "[\"Wifi\",\"Klima\",\"Balkon\",\"Plaja Yak\\u0131n\",\"Deniz Manzaras\\u0131\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 10, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Konyaaltı sahilinde, plaja 50m mesafede modern daire. Balkondan deniz manzarası.",
                            Guests = 3,
                            IsArchived = false,
                            Latitude = 36.859699999999997,
                            Longitude = 30.625599999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1900m,
                            Title = "Antalya Konyaaltı Plaj Dairesi",
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            AccommodationType = "Bütün mekan",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Fethiye",
                            AddressPostalCode = "48300",
                            AddressRegion = "Ege",
                            AddressStreet = "Ovacık Mahallesi, Çam Sokak No:19",
                            Amenities = "[\"Wifi\",\"Klima\",\"Bah\\u00E7e\",\"Mangal\",\"Otopark\",\"Do\\u011Fa\"]",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            Beds = 3,
                            CreatedAt = new DateTime(2024, 11, 2, 15, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Ölüdeniz lagününe 15 dakika yürüme mesafesinde, geniş bahçeli müstakil ev.",
                            Guests = 5,
                            IsArchived = false,
                            Latitude = 36.549999999999997,
                            Longitude = 29.116700000000002,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800\"]",
                            PlaceType = "Ev",
                            Price = 2800m,
                            Title = "Fethiye Ölüdeniz'de Bahçeli Ev",
                            UserId = 4
                        },
                        new
                        {
                            Id = 10,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Kat:4",
                            AddressCity = "İzmir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Konak",
                            AddressPostalCode = "35360",
                            AddressRegion = "Ege",
                            AddressStreet = "Kemeraltı Mahallesi, Anafartalar Caddesi No:56",
                            Amenities = "[\"Wifi\",\"Klima\",\"\\u015Eehir Manzaras\\u0131\",\"Merkezi Konum\",\"Tarihi Bina\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "İzmir Konak'ta tarihi binada restore edilmiş loft daire. Şehir manzarası ve modern tasarım.",
                            Guests = 4,
                            IsArchived = false,
                            Latitude = 38.418900000000001,
                            Longitude = 27.128699999999998,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1700m,
                            Title = "Konak Meydanı Manzaralı Loft",
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa Mavi",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Marmaris",
                            AddressPostalCode = "48700",
                            AddressRegion = "Ege",
                            AddressStreet = "İçmeler Mahallesi, Deniz Yolu No:42",
                            Amenities = "[\"Wifi\",\"Havuz\",\"Klima\",\"Teras\",\"Deniz Manzaras\\u0131\",\"BBQ\"]",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            Beds = 4,
                            CreatedAt = new DateTime(2024, 11, 3, 12, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Marmaris merkezine yakın, özel havuzlu triplex villa. Deniz manzarası ve geniş teras.",
                            Guests = 6,
                            IsArchived = false,
                            Latitude = 36.851300000000002,
                            Longitude = 28.2744,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800\"]",
                            PlaceType = "Villa",
                            Price = 4200m,
                            Title = "Marmaris Havuzlu Triplex Villa",
                            UserId = 4
                        },
                        new
                        {
                            Id = 12,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Bungalov 12",
                            AddressCity = "Sakarya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Sapanca",
                            AddressPostalCode = "54600",
                            AddressRegion = "Marmara",
                            AddressStreet = "Göl Mahallesi, Kıyı Yolu No:67",
                            Amenities = "[\"Wifi\",\"\\u015E\\u00F6mine\",\"Jakuzi\",\"G\\u00F6l Manzaras\\u0131\",\"Do\\u011Fa\",\"\\u00D6zel Plaj\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 1,
                            CreatedAt = new DateTime(2024, 11, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sapanca Gölü kenarında romantik bungalov. Şömine, jakuzi ve göl manzarası.",
                            Guests = 2,
                            IsArchived = false,
                            Latitude = 40.689399999999999,
                            Longitude = 30.267800000000001,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800\"]",
                            PlaceType = "Kulübe",
                            Price = 2100m,
                            Title = "Sapanca Göl Kenarı Bungalov",
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Kat:3",
                            AddressCity = "İstanbul",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Kadıköy",
                            AddressPostalCode = "34710",
                            AddressRegion = "Marmara",
                            AddressStreet = "Moda Caddesi No:134",
                            Amenities = "[\"Wifi\",\"Klima\",\"Merkezi Konum\",\"Mutfak\",\"Balkon\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 1, 16, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Moda'da nostaljik apartman dairesinde konforlu konaklama. Yürüyüş mesafesinde cafe ve restoranlar.",
                            Guests = 4,
                            IsArchived = false,
                            Latitude = 40.987200000000001,
                            Longitude = 29.026399999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1600m,
                            Title = "Kadıköy'de Nostaljik Daire",
                            UserId = 5
                        },
                        new
                        {
                            Id = 14,
                            AccommodationType = "Bütün mekan",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Side",
                            AddressPostalCode = "07330",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Selimiye Mahallesi, Antik Yol No:28",
                            Amenities = "[\"Wifi\",\"Havuz\",\"Klima\",\"Bah\\u00E7e\",\"Otopark\",\"Merkezi Konum\"]",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            Beds = 4,
                            CreatedAt = new DateTime(2024, 11, 2, 10, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Side antik kente yürüme mesafesinde, havuzlu müstakil ev. Aile ve arkadaş grupları için ideal.",
                            Guests = 7,
                            IsArchived = false,
                            Latitude = 36.767299999999999,
                            Longitude = 31.3902,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800\"]",
                            PlaceType = "Ev",
                            Price = 3800m,
                            Title = "Side Antik Kent Yakını Villa",
                            UserId = 5
                        },
                        new
                        {
                            Id = 15,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Kat:5",
                            AddressCity = "İstanbul",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Beyoğlu",
                            AddressPostalCode = "34433",
                            AddressRegion = "Marmara",
                            AddressStreet = "Cihangir Mahallesi, Firuzağa Sokak No:23",
                            Amenities = "[\"Wifi\",\"Merkezi Konum\",\"\\u015Eehir Manzaras\\u0131\",\"Sanat Galerisi Yak\\u0131n\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 5, 11, 30, 0, 0, DateTimeKind.Utc),
                            Description = "İstiklal Caddesi'ne 5 dakika, sanatçı mahallesinde bohem loft daire.",
                            Guests = 3,
                            IsArchived = false,
                            Latitude = 41.031700000000001,
                            Longitude = 28.978300000000001,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1500m,
                            Title = "Beyoğlu'nda Sanatçı Loft'u",
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa Exclusive",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Gökova",
                            AddressPostalCode = "48650",
                            AddressRegion = "Ege",
                            AddressStreet = "Akyaka Mahallesi, Körfez Yolu No:5",
                            Amenities = "[\"Wifi\",\"Sonsuzluk Havuzu\",\"\\u00D6zel \\u0130skele\",\"\\u00D6zel Plaj\",\"Jakuzi\",\"Sauna\",\"Bah\\u00E7e\"]",
                            Bathrooms = 5,
                            Bedrooms = 6,
                            Beds = 8,
                            CreatedAt = new DateTime(2024, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gökova Körfezi'nde özel iskele ve tekne bağlama imkanı olan mega villa. Sonsuzluk havuzu ve özel plaj.",
                            Guests = 12,
                            IsArchived = false,
                            Latitude = 37.045299999999997,
                            Longitude = 28.321100000000001,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800\"]",
                            PlaceType = "Villa",
                            Price = 8500m,
                            Title = "Gökova Körfezi Lüks Villa",
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            AccommodationType = "Özel oda",
                            AddressBuilding = "Mağara Kat:2",
                            AddressCity = "Nevşehir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Göreme",
                            AddressPostalCode = "50180",
                            AddressRegion = "İç Anadolu",
                            AddressStreet = "Müze Caddesi No:12",
                            Amenities = "[\"Wifi\",\"Kahvalt\\u0131 Dahil\",\"Balon Turu\",\"Tarihi Mekan\",\"Teras\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 1,
                            CreatedAt = new DateTime(2024, 11, 3, 7, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Göreme'de otantik mağara otel odası. Balon turu dahil, terasta kahvaltı servisi.",
                            Guests = 2,
                            IsArchived = false,
                            Latitude = 38.643099999999997,
                            Longitude = 34.828099999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800\"]",
                            PlaceType = "Otel Odası",
                            Price = 2700m,
                            Title = "Kapadokya Mağara Otel",
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "C Blok Kat:8",
                            AddressCity = "İzmir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Alsancak",
                            AddressPostalCode = "35220",
                            AddressRegion = "Ege",
                            AddressStreet = "Kıbrıs Şehitleri Caddesi No:145",
                            Amenities = "[\"Wifi\",\"Klima\",\"Marina Manzaras\\u0131\",\"Balkon\",\"Merkezi Konum\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 3,
                            CreatedAt = new DateTime(2024, 11, 4, 13, 15, 0, 0, DateTimeKind.Utc),
                            Description = "İzmir Alsancak'ta marina ve deniz manzaralı modern daire. Gece hayatına yürüme mesafesinde.",
                            Guests = 5,
                            IsArchived = false,
                            Latitude = 38.438200000000002,
                            Longitude = 27.1463,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800\"]",
                            PlaceType = "Daire",
                            Price = 2000m,
                            Title = "Alsancak Marina Manzaralı Daire",
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Şale 15",
                            AddressCity = "Bursa",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Uludağ",
                            AddressPostalCode = "16370",
                            AddressRegion = "Marmara",
                            AddressStreet = "Oteller Bölgesi No:78",
                            Amenities = "[\"Wifi\",\"\\u015E\\u00F6mine\",\"Jakuzi\",\"Kayak Pisti Yak\\u0131n\",\"Da\\u011F Manzaras\\u0131\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 2, 8, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Uludağ'da piste yakın modern şale. Şömine, jakuzi ve dağ manzarası.",
                            Guests = 4,
                            IsArchived = false,
                            Latitude = 40.102499999999999,
                            Longitude = 29.087800000000001,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1542718610-a1d656d1884c?w=800\"]",
                            PlaceType = "Kulübe",
                            Price = 3200m,
                            Title = "Uludağ Kayak Merkezi Şale",
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            AccommodationType = "Bütün mekan",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Datça",
                            AddressPostalCode = "48900",
                            AddressRegion = "Ege",
                            AddressStreet = "Eski Datça Mahallesi, Badem Sokak No:34",
                            Amenities = "[\"Wifi\",\"Bah\\u00E7e\",\"Veranda\",\"Tarihi Ev\",\"Do\\u011Fa\",\"Huzurlu\"]",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            Beds = 3,
                            CreatedAt = new DateTime(2024, 11, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eski Datça'da restore edilmiş otantik taş ev. Bahçe, veranda ve sessiz konum.",
                            Guests = 6,
                            IsArchived = false,
                            Latitude = 36.726399999999998,
                            Longitude = 27.688099999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800\"]",
                            PlaceType = "Ev",
                            Price = 2900m,
                            Title = "Datça Eski Datça Taş Ev",
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa Green",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Belek",
                            AddressPostalCode = "07506",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Golf Mahallesi, Yeşil Alan Caddesi No:56",
                            Amenities = "[\"Wifi\",\"Havuz\",\"Golf Sahas\\u0131\",\"Spa Yak\\u0131n\",\"Klima\",\"Bah\\u00E7e\"]",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            Beds = 5,
                            CreatedAt = new DateTime(2024, 11, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Belek'te golf sahası manzaralı, özel havuzlu lüks villa. Spa ve fitness merkezi yakın.",
                            Guests = 8,
                            IsArchived = false,
                            Latitude = 36.862499999999997,
                            Longitude = 31.055299999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800\"]",
                            PlaceType = "Villa",
                            Price = 5200m,
                            Title = "Belek Golf Sahalı Villa",
                            UserId = 4
                        },
                        new
                        {
                            Id = 22,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Site A Blok Kat:4",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Bodrum",
                            AddressPostalCode = "48400",
                            AddressRegion = "Ege",
                            AddressStreet = "Gümbet Mahallesi, Plaj Yolu No:89",
                            Amenities = "[\"Wifi\",\"Klima\",\"Havuz\",\"Plaja Yak\\u0131n\",\"G\\u00FCvenlik\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 3, 15, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Gümbet plajına 2 dakika, site içinde havuzlu modern daire.",
                            Guests = 3,
                            IsArchived = false,
                            Latitude = 37.030299999999997,
                            Longitude = 27.407800000000002,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1800m,
                            Title = "Bodrum Gümbet Plaj Dairesi",
                            UserId = 4
                        },
                        new
                        {
                            Id = 23,
                            AccommodationType = "Bütün mekan",
                            AddressCity = "Çanakkale",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Assos",
                            AddressPostalCode = "17860",
                            AddressRegion = "Marmara",
                            AddressStreet = "Behramkale Köyü, Liman Yolu No:12",
                            Amenities = "[\"Wifi\",\"Bah\\u00E7e\",\"Deniz Manzaras\\u0131\",\"Do\\u011Fa\",\"Tarihi Alan Yak\\u0131n\"]",
                            Bathrooms = 2,
                            Bedrooms = 2,
                            Beds = 3,
                            CreatedAt = new DateTime(2024, 11, 4, 11, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Assos antik limanına 10 dakika, köy evinde huzurlu tatil. Bahçe ve deniz manzarası.",
                            Guests = 5,
                            IsArchived = false,
                            Latitude = 39.491900000000001,
                            Longitude = 26.338899999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800\"]",
                            PlaceType = "Ev",
                            Price = 2300m,
                            Title = "Çanakkale Assos Köy Evi",
                            UserId = 5
                        },
                        new
                        {
                            Id = 24,
                            AccommodationType = "Özel oda",
                            AddressBuilding = "Butik Otel Kat:2",
                            AddressCity = "İzmir",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Şirince",
                            AddressPostalCode = "35920",
                            AddressRegion = "Ege",
                            AddressStreet = "Köy Merkezi No:45",
                            Amenities = "[\"Wifi\",\"Kahvalt\\u0131 Dahil\",\"\\u015Earap Tad\\u0131m\\u0131\",\"Tarihi Mekan\",\"Do\\u011Fa\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 1,
                            CreatedAt = new DateTime(2024, 11, 5, 8, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Şirince köyünde tarihi butik otel odası. Şarap tadımı ve kahvaltı dahil.",
                            Guests = 2,
                            IsArchived = false,
                            Latitude = 37.945599999999999,
                            Longitude = 27.448899999999998,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800\"]",
                            PlaceType = "Otel Odası",
                            Price = 1400m,
                            Title = "Şirince Butik Otel Odası",
                            UserId = 5
                        },
                        new
                        {
                            Id = 25,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa Orange",
                            AddressCity = "Muğla",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Bodrum",
                            AddressPostalCode = "48470",
                            AddressRegion = "Ege",
                            AddressStreet = "Bitez Mahallesi, Mandalina Sokak No:67",
                            Amenities = "[\"Wifi\",\"Havuz\",\"Klima\",\"Bah\\u00E7e\",\"Denize Yak\\u0131n\",\"Mangal\"]",
                            Bathrooms = 4,
                            Bedrooms = 5,
                            Beds = 6,
                            CreatedAt = new DateTime(2024, 11, 2, 14, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Bitez'de mandalina bahçeleri arasında, denize yakın özel havuzlu villa.",
                            Guests = 10,
                            IsArchived = false,
                            Latitude = 37.0167,
                            Longitude = 27.383299999999998,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800\"]",
                            PlaceType = "Villa",
                            Price = 4800m,
                            Title = "Bitez Mandalinakoy Villa",
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "B Blok Kat:6",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Alanya",
                            AddressPostalCode = "07400",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Saray Mahallesi, Kleopatra Caddesi No:234",
                            Amenities = "[\"Wifi\",\"Klima\",\"Balkon\",\"Plaja Yak\\u0131n\",\"Deniz Manzaras\\u0131\"]",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 3, 16, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kleopatra plajına 100m, deniz manzaralı balkonlu modern daire.",
                            Guests = 4,
                            IsArchived = false,
                            Latitude = 36.543300000000002,
                            Longitude = 31.985600000000002,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1650m,
                            Title = "Alanya Kleopatra Plajı Dairesi",
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Ev 8",
                            AddressCity = "Rize",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Ayder",
                            AddressPostalCode = "53750",
                            AddressRegion = "Karadeniz",
                            AddressStreet = "Yayla Mahallesi, Dere Yolu No:23",
                            Amenities = "[\"Wifi\",\"\\u015E\\u00F6mine\",\"Do\\u011Fa\",\"Dere Kenar\\u0131\",\"Huzurlu\",\"Da\\u011F Manzaras\\u0131\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 1,
                            CreatedAt = new DateTime(2024, 11, 1, 7, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ayder'de dere kenarında ahşap dağ evi. Şömine, doğa ve huzur.",
                            Guests = 2,
                            IsArchived = false,
                            Latitude = 40.966700000000003,
                            Longitude = 40.916699999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800\"]",
                            PlaceType = "Kulübe",
                            Price = 1900m,
                            Title = "Ayder Yaylaı Dağ Evi",
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Kat:2",
                            AddressCity = "Antalya",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Kaleiçi",
                            AddressPostalCode = "07100",
                            AddressRegion = "Akdeniz",
                            AddressStreet = "Barbaros Mahallesi, Hesapçı Sokak No:18",
                            Amenities = "[\"Wifi\",\"Klima\",\"Tarihi Bina\",\"Merkezi Konum\",\"Marina Yak\\u0131n\"]",
                            Bathrooms = 1,
                            Bedrooms = 1,
                            Beds = 2,
                            CreatedAt = new DateTime(2024, 11, 4, 9, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Kaleiçi'nde restore edilmiş tarihi binada modern daire. Marina ve müzelere yürüme mesafesinde.",
                            Guests = 3,
                            IsArchived = false,
                            Latitude = 36.884099999999997,
                            Longitude = 30.7056,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800\"]",
                            PlaceType = "Daire",
                            Price = 1750m,
                            Title = "Antalya Kaleiçi Tarihi Daire",
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            AccommodationType = "Bütün mekan",
                            AddressBuilding = "Villa Sea",
                            AddressCity = "Aydın",
                            AddressCountry = "Türkiye",
                            AddressDistrict = "Kuşadası",
                            AddressPostalCode = "09400",
                            AddressRegion = "Ege",
                            AddressStreet = "Kadınlar Denizi Mahallesi, Sahil Yolu No:91",
                            Amenities = "[\"Wifi\",\"Havuz\",\"Klima\",\"Bah\\u00E7e\",\"Plaja Yak\\u0131n\",\"Otopark\"]",
                            Bathrooms = 3,
                            Bedrooms = 4,
                            Beds = 5,
                            CreatedAt = new DateTime(2024, 11, 2, 13, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Ladies Beach'e 5 dakika, özel havuzlu ve bahçeli geniş villa.",
                            Guests = 9,
                            IsArchived = false,
                            Latitude = 37.857500000000002,
                            Longitude = 27.258099999999999,
                            PhotoUrls = "[\"https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800\"]",
                            PlaceType = "Villa",
                            Price = 4500m,
                            Title = "Kuşadası Ladies Beach Villa",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("StayIn.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Favorites")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerificationCodeExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet@example.com",
                            Favorites = "[]",
                            FullName = "Ahmet Yılmaz",
                            PasswordHash = "$2a$11$5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5OqK5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3",
                            PhoneNumber = "05321112233",
                            Role = "User"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse@stayin.dev",
                            Favorites = "[]",
                            FullName = "Ayşe Demir",
                            PasswordHash = "$2a$11$5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5OqK5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3",
                            PhoneNumber = "05334445566",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mehmet@stayin.dev",
                            Favorites = "[]",
                            FullName = "Mehmet Kaya",
                            PasswordHash = "$2a$11$5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5OqK5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3",
                            PhoneNumber = "05347778899",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "zeynep@stayin.dev",
                            Favorites = "[]",
                            FullName = "Zeynep Şahin",
                            PasswordHash = "$2a$11$5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5OqK5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3",
                            PhoneNumber = "05352223344",
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "can@stayin.dev",
                            Favorites = "[]",
                            FullName = "Can Öztürk",
                            PasswordHash = "$2a$11$5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5OqK5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3Z5Z3",
                            PhoneNumber = "05368889900",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("StayIn.Api.Models.Listing", b =>
                {
                    b.HasOne("StayIn.Api.Models.User", "User")
                        .WithMany("Listings")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StayIn.Api.Models.User", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
